//! Writes `src/unicode_tables.rs`: the pre-tokenizer regex's character classes, from the
//! reference probe that oracle/tokenizer_goldens.py records in
//! oracle/goldens/tokenizer/unicode_classes.json.
//!
//! ```text
//! cargo run -p glm53f-tokenizer --example gen_unicode_tables -- \
//!     oracle/goldens/tokenizer/unicode_classes.json > crates/glm53f-tokenizer/src/unicode_tables.rs
//! ```
//!
//! It compiles the crate's JSON reader in by path, so it runs even when the tables file it
//! replaces does not build.

#[allow(dead_code)]
#[path = "../src/json.rs"]
mod json;

fn main() {
    let path = std::env::args().nth(1).expect("usage: gen_unicode_tables <unicode_classes.json>");
    let text = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{path}: {e}"));
    let doc = json::parse(&text).unwrap_or_else(|e| panic!("{path}: {e}"));
    println!("// Generated by examples/gen_unicode_tables.rs from oracle/goldens/tokenizer/unicode_classes.json:");
    println!("// the pre-tokenizer regex's classes, probed from the reference tokenizer. Do not edit by hand.");
    let classes = [
        ("LETTER", "L", "Letters: the regex's \\p{L}."),
        ("NUMBER", "N", "Numbers: the regex's \\p{N}."),
        ("SPACE", "S", "Whitespace: the regex's \\s."),
    ];
    for (name, key, doc_line) in classes {
        let ranges = doc.get(key).and_then(|r| r.as_array()).unwrap_or_else(|| panic!("no {key} array"));
        println!();
        println!("/// {doc_line} Inclusive code point ranges, ascending.");
        println!("pub(crate) static {name}: [(u32, u32); {}] = [", ranges.len());
        for chunk in ranges.chunks(4) {
            let row: Vec<String> = chunk
                .iter()
                .map(|r| {
                    let pair = r.as_array().expect("range pair");
                    let lo = pair[0].as_u64().expect("range start");
                    let hi = pair[1].as_u64().expect("range end");
                    assert!(lo <= hi && hi <= 0x10FFFF, "bad range {lo}..{hi}");
                    format!("(0x{lo:05X}, 0x{hi:05X})")
                })
                .collect();
            println!("    {},", row.join(", "));
        }
        println!("];");
    }
}
